services:
    Symfgenus\MpdfWrapper\Service\MpdfService:
        class: Symfgenus\MpdfWrapper\Service\MpdfService
        public: false
        
    symfgenus.mpdf.wrapper:
        alias: '@Symfgenus\MpdfWrapper\Service\MpdfService'
        public: true