services:
    Symfgenus\MpdfWrapper\MpdfService:
        arguments: ["%kernel.cache_dir%"]
        public: false
        
    symfgenus.mpdf.wrapper:
        alias: Symfgenus\MpdfWrapper\MpdfService
        public: true